version: '3.1'
services:

  app:
    image: dharini/spring-react-mongo-docker
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:4.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d