version: '3.1'
services:
  mongo:
    image: bitnami/mongodb:4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    volumes:
      - ./mongodb_data:/bitnami
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
